# version: '3.8'

services:
  app:
    build: .
    container_name: classroombookings
    volumes:
      - .:/var/www/html
    ports:
      - "1280:80"
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=classroombookings
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - APP_DEBUG=true
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: classroombookings_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: classroombookings
      MYSQL_USER: crbs_user
      MYSQL_PASSWORD: crbs_password
      TZ: Europe/Paris
    command: >
      --default-authentication-plugin=mysql_native_password
      --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mariadb

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_crbs
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: