name: Deploy ClassroomBooking App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Source Files and Build on `ultratrail`
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Configure SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add SSH configuration
          printf "Host patriot\n  HostName patriot.lkb.upmc.fr\n  User glorieux\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no\n" >> ~/.ssh/config
          printf "Host ultratrail\n  HostName ultratrail.lkb.upmc.fr\n  User adminultra\n  ProxyJump patriot\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no\n" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

          # Transfer source files to the server
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ adminultra@ultratrail:/home/adminultra/classroombooking-source/

          # SSH into the server, move directories, and copy assets/css
          ssh ultratrail << 'EOF'
            cd /home/adminultra/classroombooking-source
            echo "Logging deployment on $(date)" >> ~/deploy-log.txt

            echo "Preparing to move core files..."
            TARGET_DIR=~/classroombookings-3.0.0
            if [ -d $TARGET_DIR ]; then
              rm -rf $TARGET_DIR
            fi

            # Move the core directory
            mv classroombookings/crbs-core/ $TARGET_DIR

            # Copy assets/css directory to the new location
            echo "Copying assets/css..."
            cp -r assets/css $TARGET_DIR/

            echo "Deployment completed successfully!"
          EOF