name: Deploy ClassroomBooking App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Source Files and Build on `ultratrail`
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Configure SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add SSH configuration
          printf "Host patriot\n  HostName patriot.lkb.upmc.fr\n  User glorieux\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no\n" >> ~/.ssh/config
          printf "Host ultratrail\n  HostName ultratrail.lkb.upmc.fr\n  User adminultra\n  ProxyJump patriot\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no\n" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

          # Transfer source files to the server
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ adminultra@ultratrail:/home/adminultra/classroombooking-source/

          # SSH into the server, move files, and copy directories
          ssh ultratrail << 'EOF'
            echo "Logging deployment on $(date)" >> ~/deploy-log.txt

            # Define source and target directories
            SRC_DIR=/home/adminultra/classroombooking-source/classroombookings
            DEST_DIR=/home/adminultra/docker/classroombookings/classroombookings-3.0.0

            # Create destination directory if it doesn't exist
            mkdir -p $DEST_DIR

            echo "Removing existing directories in the destination..."
            rm -rf $DEST_DIR/crbs-core
            rm -rf $DEST_DIR/assets/css

            echo "Copying crbs-core..."
            cp -r $SRC_DIR/crbs-core $DEST_DIR/

            echo "Copying assets/css..."
            mkdir -p $DEST_DIR/assets
            cp -r $SRC_DIR/assets/css $DEST_DIR/assets/

            echo "Deployment completed successfully!"
          EOF