name: Deploy ClassroomBooking App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3


      # Step 2: Deploy Application via SSH ProxyJump
      - name: Deploy Application via SSH ProxyJump
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Configure SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add SSH configuration with ProxyJump
          printf "Host patriot\n  HostName patriot.lkb.upmc.fr\n  User glorieux\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no\n" >> ~/.ssh/config
          printf "Host ultratrail\n  HostName ultratrail.lkb.upmc.fr\n  User adminultra\n  ProxyJump patriot\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no\n" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

          # Test SSH connection
          ssh -o StrictHostKeyChecking=no ultratrail echo "SSH connection successful"

          # Clone repository on the server
          ssh ultratrail <<EOF
            echo "Logging new deployment on $(date)" >> ~/deploy-log.txt

            echo "Cloning repository..."
            if [ -d ~/classroombooking ]; then
              rm -rf ~/classroombooking
            fi
            git clone https://github.com/quentinglorieux/classroombooking.git ~/classroombooking

            echo "Moving core files to the target directory..."
            TARGET_DIR=~/classroombookings-3.0.0
            if [ -d $TARGET_DIR ]; then
              rm -rf $TARGET_DIR
            fi
            mv ~/classroombooking/classroombookings/crbs-core/ $TARGET_DIR

            echo "Deployment completed successfully!"
          EOF